[
    {
        "key": "sb",
        "value": "Zg7-aECWN8ZN7EFbQgf81SEg",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.530Z",
        "lastAccessed": "2025-11-20T11:00:27.531Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B694x384x2.8125",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.531Z",
        "lastAccessed": "2025-11-20T11:00:27.531Z"
    },
    {
        "key": "ps_l",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.531Z",
        "lastAccessed": "2025-11-20T11:00:27.531Z"
    },
    {
        "key": "ps_n",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.531Z",
        "lastAccessed": "2025-11-20T11:00:27.531Z"
    },
    {
        "key": "locale",
        "value": "en_US",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.531Z",
        "lastAccessed": "2025-11-20T11:00:27.531Z"
    },
    {
        "key": "m_pixel_ratio",
        "value": "2.8125",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.532Z",
        "lastAccessed": "2025-11-20T11:00:27.532Z"
    },
    {
        "key": "wd",
        "value": "384x832",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.532Z",
        "lastAccessed": "2025-11-20T11:00:27.532Z"
    },
    {
        "key": "datr",
        "value": "UvQeadkj5jK1tqRLtEjbNbCs",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.532Z",
        "lastAccessed": "2025-11-20T11:00:27.532Z"
    },
    {
        "key": "c_user",
        "value": "100088291997056",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.532Z",
        "lastAccessed": "2025-11-20T11:00:27.532Z"
    },
    {
        "key": "xs",
        "value": "3%3AAIBE9Fm86kgCyg%3A2%3A1763636385%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.532Z",
        "lastAccessed": "2025-11-20T11:00:27.532Z"
    },
    {
        "key": "fr",
        "value": "070fsUk1aIrtV1Zpw.AWepKy7mDOHCS7E2fvc0VLNRF5esFapIetJ5rVU1qYRVi5Fy5Ys.Bo_g5m..AAA.0.0.BpHvSl.AWe2cgJeMv05_zwPjgKIl3jmBuM",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.532Z",
        "lastAccessed": "2025-11-20T11:00:27.532Z"
    },
    {
        "key": "pas",
        "value": "100088291997056%3AGJWAQbhT2g",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.532Z",
        "lastAccessed": "2025-11-20T11:00:27.532Z"
    },
    {
        "key": "fbl_st",
        "value": "101438087%3BT%3A29393939",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.532Z",
        "lastAccessed": "2025-11-20T11:00:27.532Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2989%3Btimestamp%3A1763636389",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-20T11:00:27.532Z",
        "lastAccessed": "2025-11-20T11:00:27.532Z"
    }
]
